name: Build demo client

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Update Submodules
        run: git submodule update --init --recursive --depth=1

      - name: Configure
        run: cmake -B build .

      - name: Build
        run: cmake --build build
